const Events = {
  START_JOIN_CHAT_ROOM: 'START_JOIN_CHAT_ROOM',
  SUCCESS_JOIN_CHAT_ROOM: 'SUCCESS_JOIN_CHAT_ROOM',
  FAILURE_JOIN_CHAT_ROOM: 'FAILURE_JOIN_CHAT_ROOM',
  UPDATE_USER_ONLINE_NUMBER: 'UPDATE_USER_ONLINE_NUMBER',
  ADD_CHAT_RECORD: 'ADD_CHAT_RECORD',
  ADD_SYSTEM_RECORD: 'ADD_SYSTEM_RECORD',
  RECONNECT_CHAT_ROOM: 'RECONNECT_CHAT_ROOM'
}

export default Events
